import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import * as apipb from "../apipb/api";
import { useListTutorials } from "../apipb/useApi";

const rpc = new apipb.GrpcWebImpl("/api", { debug: true });
const api = new apipb.TutorialsClientImpl(rpc);

const Home: NextPage = () => {
  const { data, error } = useListTutorials(api, { pageSize: 10 });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">Next.js</a> with{" "}
          <a href="https://larking.io">Larking.io</a>
        </h1>

        <p className={styles.description}>Demo showcasing gRPC-Web</p>
        {error && <div className={styles.code}>{error.message}</div>}

        <div className={styles.grid}>
          {data?.tutorials?.map?.((tutorial, i) => (
            <a key={i} href={tutorial.url} className={styles.card}>
              <h2>{tutorial.title} &rarr;</h2>
              <p>{tutorial.subTitle}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://larking.io" target="_blank" rel="noopener noreferrer">
          Hello
        </a>
      </footer>
    </div>
  );
};

export default Home;
